### ISSUE TITLE
Bukkit plugin doesn't work on BungeeCord network

### ISSUE THREAD

**Issue by Ghost-chu** [ModProg/BlockMeter#10]
```
[17:22:06 WARN]: [SpigotBlockMeterReflector] Plugin SpigotBlockMeterReflector v1.4.1 generated an exception whilst handling plugin message
>java.lang.NullPointerException: null
at de.guntram.bukkit.SpigotBlockMeterReflector.Main.buildS2CPacket(Main.java:60) ~[?:?]
at de.guntram.bukkit.SpigotBlockMeterReflector.Main.informAllPlayers(Main.java:48) ~[?:?]
at de.guntram.bukkit.SpigotBlockMeterReflector.Main.onPluginMessageReceived(Main.java:44) ~[?:?]
at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:455) ~[patched_1.16.1.jar:git-Paper-131]
at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:2769) ~[patched_1.16.1.jar:git-Paper-131]
at net.minecraft.server.v1_16_R1.PacketPlayInCustomPayload.a(SourceFile:44) ~[patched_1.16.1.jar:git-Paper-131]
at net.minecraft.server.v1_16_R1.PacketPlayInCustomPayload.a(SourceFile:9) ~[patched_1.16.1.jar:git-Paper-131]
at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.1.jar:git-Paper-131]
at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18) ~[patched_1.16.1.jar:git-Paper-131]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.1.jar:git-Paper-131]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.1.jar:git-Paper-131]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.1.jar:git-Paper-131]
at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1137) ~[patched_1.16.1.jar:git-Paper-131]
at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1130) ~[patched_1.16.1.jar:git-Paper-131]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.1.jar:git-Paper-131]
at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1091) ~[patched_1.16.1.jar:git-Paper-131]
at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1005) ~[patched_1.16.1.jar:git-Paper-131]
at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-131]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
```
![image](https://user-images.githubusercontent.com/30802565/89632733-3f4f0b80-d8d5-11ea-9a44-766ce1840028.png)

**Comment by ModProg** [comment]
Could you maybe further specify your setup, it is currently working for me with BungeeCord and CraftBukkit/Spiggot.
The only problem with the current version of the Mod is a labelling error meaning you need to set the setting show boxes of other players to NO.

**Comment by Ghost-chu** [comment]
Setup:
BungeeCord: WaterFall #366
Plugins(BC): ViaVersion + ViaRewind + ViaBackwards
Spigot: Paper (1.16.1) #131

**Comment by ModProg** [comment]
Could you try it with the up to date version of the mod:
https://www.curseforge.com/minecraft/mc-mods/blockmeterfabric/files/3025936
I will investigate this further but I wasn't able to reproduce it yet.

**Comment by Ghost-chu** [comment]
![image](https://user-images.githubusercontent.com/30802565/89662964-67576280-d907-11ea-8b61-d8473c18a27d.png)
Cool, It's looks fixed!
