### ISSUE TITLE
Crashes on 1.19.4

### ISSUE THREAD

**Issue by KadTheHunter** [ModProg/BlockMeter#38]
Tested the newest release (1.19.3) on 1.19.4, it loads fine, and you can enable it fine, but clicking to set the first position crashes the game.

Error is as below:
```[14:56:10] [Render thread/ERROR]: Unreported exception thrown!
java.lang.NoSuchMethodError: 'void com.mojang.blaze3d.systems.RenderSystem.disableTexture()'
	at win.baruna.blockmeter.measurebox.ClientMeasureBox.render(ClientMeasureBox.java:144) ~[blockmeter-1.8-HEAD.jar:?]
	at win.baruna.blockmeter.measurebox.ClientMeasureBox.render(ClientMeasureBox.java:122) ~[blockmeter-1.8-HEAD.jar:?]
	at win.baruna.blockmeter.BlockMeterClient.lambda$renderOverlay$4(BlockMeterClient.java:202) ~[blockmeter-1.8-HEAD.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at win.baruna.blockmeter.BlockMeterClient.renderOverlay(BlockMeterClient.java:202) ~[blockmeter-1.8-HEAD.jar:?]
	at net.minecraft.class_757.handler$zzd000$blockmeter$onRenderCenterLast(class_757.java:2094) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3188(class_757.java:1124) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:872) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1218) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:801) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:237) ~[minecraft-1.19.4-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) ~[fabric-loader-0.14.18.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.18.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.18.jar:?]
```

**Comment by ModProg** [comment]
let me know if it doesn't work

**Comment by KadTheHunter** [comment]
Just tried it, has the same error.

Only have BlockMeter 1.9 and Fabric API,

@ModProg

**Comment by ModProg** [comment]
That is strange, I though I tested it

**Comment by ModProg** [comment]
Should be working now, https://modrinth.com/mod/blockmeter/version/v1.9.1

**Comment by KadTheHunter** [comment]
Works perfect now, thanks!!
